defaults:
  - train
  - _self_

idx_t0: 40
idx_t1: 160
N0: 199
N1: 201
q: 50
discrete: True

time_domain:
  _target_: pinnstf2.data.TimeDomain
  t_interval: [0, 1]
  t_points: 201

spatial_domain:
  _target_: pinnstf2.data.Interval
  x_interval: [-1, 1]
  shape: [512, 1]

mesh:
  _target_: pinnstf2.data.Mesh
  root_dir: ${paths.data_dir}
  read_data_fn: ???

runge_kutta:
  _target_: pinnstf2.models.RungeKutta
  root_dir: ${paths.rk_dir}
  q: ${q}
  t1: ${idx_t0}
  t2: ${idx_t1}
  time_domain: ${time_domain}

train_datasets:
  - mesh_sampler:
      _target_: pinnstf2.data.DiscreteMeshSampler
      _partial_: true
      num_sample: ${N0}
      idx_t: ${idx_t0}
      solution:
        - u
      collection_points:
        - f

  - mesh_sampler:
      _target_: pinnstf2.data.DiscreteMeshSampler
      _partial_: true
      num_sample: ${N1}
      idx_t: ${idx_t1}
      solution:
        - u
      collection_points:
        - f

val_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.DiscreteMeshSampler
      _partial_: true
      idx_t: ${idx_t1}
      solution:
        - u

pred_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.DiscreteMeshSampler
      _partial_: true
      idx_t: ${idx_t1}
      solution:
        - u

net:
  _target_: pinnstf2.models.FCN
  layers:
    - 1
    - 50
    - 50
    - 50
    - ${q}
  output_names:
    - u
  discrete: ${discrete}

model:
  runge_kutta: ${runge_kutta}
  extra_variables:
    l1: 0.0
    l2: -6.0
  jit_compile: false

trainer:
  max_epochs: 50000
  check_val_every_n_epoch: 50001

train: true
val: true
test: false
optimized_metric:
  error:
    - u
  extra_variables:
    - l1
    - l2

plotting:
  _target_: pinnstf2.utils.plot_kdv
  _partial_: true

task_name: kdv

hydra:
  searchpath:
    - pkg://pinnstf2/conf
